apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- route.yaml
- configmap.yaml
- secretmap.yaml

images:
- name: quay.io/linxianer12/be
- name: quay.io/linxianer12/bootcamp-be
  newName: quay.io/linxianer12/bootcamp-be
  newTag: 0.0.23-SNAPSHOT.0
