apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
- files:
  - config.js
  name: web-portal
  
generatorOptions:
  disableNameSuffixHash: true
  
resources:
- deployment.yaml
- service.yaml
- route.yaml

images:
- name: quay.io/linxianer12/bootcamp-fe
  newName: quay.io/linxianer12/bootcamp-fe
  newTag: 0.1.4-SNAPSHOT.0
- name: quay.io/linxianer12/fe
